# Generated by Django 5.2.13 on 2026-04-28 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='commentaire',
            new_name='avis',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='note',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='inconnu@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
